export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const ADD_SEARCH_CRITERIA = 'ADD_SEARCH_CRITERIA';

export const CURRENT_USER_PROFILE = 'CURRENT_USER_PROFILE';
export const CURRENT_USER_PROFILE_ERROR = 'CURRENT_USER_PROFILE_ERROR';
export const GET_SUMMONER_DETAILS = 'GET_SUMMONER_DETAILS';
export const GET_SUMMONER_DETAILS_ERROR = 'GET_SUMMONER_DETAILS_ERROR';
export const SET_PROFILE_VISIBILITY = 'SET_PROFILE_VISIBILITY';
export const SET_PROFILE_VISIBILITY_ERROR = 'SET_PROFILE_VISIBILITY_ERROR';
export const VERIFY_SUMMONER_PROFILE = 'VERIFY_SUMMONER_PROFILE';
export const VERIFY_SUMMONER_PROFILE_ERROR = 'VERIFY_SUMMONER_PROFILE_ERROR';
export const UNVERIFY_SUMMONER_PROFILE = 'UNVERIFY_SUMMONER_PROFILE';
export const UNVERIFY_SUMMONER_PROFILE_ERROR = 'UNVERIFY_SUMMONER_PROFILE_ERROR';
export const GET_PROFILE_LIST = 'GET_PROFILE_LIST';
export const GET_PROFILE_LIST_ERROR = 'GET_PROFILE_LIST_ERROR';
